#!/usr/bin/env python3
"""Summarize scheduled Stable checks without building experimental APKs.

This is deliberately offline: the workflow supplies metadata generated by
update_supported.py and the exact published GitHub asset-name list. Matching
the release asset name (app + version + patch tag) mirrors build.yml.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

from asset_naming import current_asset

APPS = (
    ("youtube", "YouTube", "Youtube"),
    ("youtube-music", "YouTube Music", "YoutubeMusic"),
    ("reddit", "Reddit", "Reddit"),
)


def evaluate(metadata: dict, assets: list[str], build_result: str, release_tag: str = "morphe-1.46.0") -> tuple[str, str]:
    tag = metadata.get("patchesTag", "")
    if not tag.startswith("v") or not tag[1:]:
        raise ValueError("Missing or invalid upstream Morphe patch tag")

    patch_version = tag.removeprefix("v")
    asset_names = set(assets)
    rows = []
    missing = 0

    for key, title, prefix in APPS:
        versions = metadata.get("apps", {}).get(key, {}).get("versions", [])
        stable = next(
            (item["version"] for item in versions if item.get("experimental") is False),
            None,
        )
        if not stable:
            raise ValueError(f"No stable Morphe target for {title}; refusing to report current")
        published = any(
            current_asset(name, key, stable, patch_version)
            for name in asset_names
        )
        if not published:
            missing += 1
        state = "Đã phát hành — bỏ qua build" if published else "Chưa có APK đúng Stable — cần build"
        rows.append(f"| {title} | `{stable}` | {'Có' if published else 'Thiếu'} | {state} |")

    if missing == 0 and build_result == "success":
        status = "no-update"
        headline = "Không có cập nhật Stable mới — không tạo release hoặc APK mới."
    elif missing == 0:
        status = "check-failed"
        headline = f"APK Stable đã có, nhưng workflow build kết thúc với trạng thái {build_result}."
    elif build_result == "success":
        status = "pending-publish"
        headline = (
            f"Có {missing} APK Stable chưa xuất hiện trong release. "
            "Build đã hoàn tất; chờ workflow Publish riêng xác nhận phát hành."
        )
    else:
        status = "check-failed"
        headline = (
            f"Có {missing} APK Stable còn thiếu và build có trạng thái {build_result}. "
            "Cần xem log của các job Patch."
        )

    report = "\n".join(
        [
            "## Báo cáo auto-build Stable (kiểm tra 6 giờ/lần)",
            "",
            f"**Kết luận: {headline}**",
            "",
            f"- Morphe patches mới nhất: **`{tag}`**",
            f"- Release duy nhất: [`{release_tag}`](../../releases/tag/{release_tag})",
            f"- Trạng thái job build: **`{build_result}`**",
            "",
            "| Ứng dụng | Phiên bản Stable mới nhất | APK trong release | Quyết định |",
            "|---|---|---|---|",
            *rows,
            "",
            "**Lưu ý:** Chỉ theo dõi phiên bản Stable do Morphe đề xuất. "
            "Bản Experimental không kích hoạt auto-build. "
            "Không tạo release mới khi tất cả APK Stable đã có.",
            "",
        ]
    )
    return status, report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata", type=Path, required=True)
    parser.add_argument("--assets", type=Path, required=True)
    parser.add_argument("--build-result", required=True)
    parser.add_argument("--release-tag", required=True)
    parser.add_argument("--summary", type=Path, required=True)
    args = parser.parse_args()

    metadata = json.loads(args.metadata.read_text(encoding="utf-8"))
    assets = json.loads(args.assets.read_text(encoding="utf-8"))
    if not isinstance(assets, list) or any(not isinstance(a, str) for a in assets):
        raise ValueError("Release assets must be a JSON array of strings")

    status, report = evaluate(metadata, assets, args.build_result, args.release_tag)
    with args.summary.open("a", encoding="utf-8") as f:
        f.write(report)

    print(report)
    if status == "no-update":
        print("::notice title=Stable update check::No new Stable versions; all three APKs are already published.")
    elif status == "check-failed":
        print("::warning title=Stable update check::Build or publication check needs attention.")
    else:
        print("::notice title=Stable update check::New Stable APK candidates detected; publishing is handled separately.")
    if os.environ.get("GITHUB_OUTPUT"):
        with open(os.environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as f:
            f.write(f"update_status={status}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
